version: '3'
services:
    database:
        image: mysql:8.0.33-oracle
        container_name: toto-main-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=my_database
            - TZ="Asia/Seoul"
        ports:
            - '3312:3306'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        stdin_open: true # `-i`
        tty: true # `-t`
